"""empty message

Revision ID: 100f6dfd0f81
Revises: 63afb4153f52
Create Date: 2021-07-18 20:07:34.327596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '100f6dfd0f81'
down_revision = '63afb4153f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolgroups', sa.Column('image_link', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahsolgroups', 'image_link')
    # ### end Alembic commands ###
