"""empty message

Revision ID: 6021da5d815f
Revises: 9cf525cc4a31
Create Date: 2021-06-02 14:31:35.756776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6021da5d815f'
down_revision = '9cf525cc4a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mahsolat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('slug', sa.String(length=128), nullable=False),
    sa.Column('group', sa.String(length=128), nullable=False),
    sa.Column('price', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mahsolat')
    # ### end Alembic commands ###
