"""empty message

Revision ID: 63afb4153f52
Revises: 47fcc383c292
Create Date: 2021-07-18 20:03:51.827573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63afb4153f52'
down_revision = '47fcc383c292'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahsolgroups', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolgroups', sa.Column('slug', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
