"""empty message

Revision ID: 6fa22bd82c8c
Revises: 98f7dbf8e995
Create Date: 2021-08-17 16:48:04.024325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fa22bd82c8c'
down_revision = '98f7dbf8e995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('metacontent', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'metacontent')
    # ### end Alembic commands ###
