"""empty message

Revision ID: 71ad7cc66c5b
Revises: 6021da5d815f
Create Date: 2021-07-06 15:44:24.157118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71ad7cc66c5b'
down_revision = '6021da5d815f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mahsolat', sa.Column('image', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mahsolat', 'image')
    # ### end Alembic commands ###
