"""empty message

Revision ID: 73871ef08d5a
Revises: 0a3955cf3710
Create Date: 2021-06-01 09:38:20.707691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '73871ef08d5a'
down_revision = '0a3955cf3710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', mysql.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
