"""empty message

Revision ID: 93b7f4999b40
Revises: 6fa22bd82c8c
Create Date: 2021-08-19 17:27:36.315230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b7f4999b40'
down_revision = '6fa22bd82c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('date', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'date')
    # ### end Alembic commands ###
