"""empty message

Revision ID: 98f7dbf8e995
Revises: 3cef768b8ece
Create Date: 2021-08-17 15:36:24.262319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f7dbf8e995'
down_revision = '3cef768b8ece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image', sa.String(length=512), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'image')
    # ### end Alembic commands ###
